---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deviceManage
  labels:
    app: deviceManage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceManage
  template:
    metadata:
      labels:
        app: deviceManage
    spec:
      containers:
        - name: deviceManage
          image: username/deviceManage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: deviceManage
  labels:
    app: deviceManage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: deviceManage

